name: Test import_github_env with ksh
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "VARNAME=value" >> $GITHUB_ENV
    - uses: twojstaryzdomu/arm-runner-action@HEAD
      with:
        import_github_env: true
        shell: ksh
        commands: |
          [ -n "${VARNAME}" ]
